### ISSUE TITLE
May I add a link to this extension to the LDPL website?

### ISSUE THREAD

**Issue by Lartu** [dvkt/vscode-ldpl#1]
What the title says, I love this!

https://marketplace.visualstudio.com/items?itemName=dvkt.vscode-ldpl

**Comment by Lartu** [comment]
I would also love if you posted about this on r/LDPL. If you don't use reddit or don't want to do such thing, I'd be glad to post it for you. I've been using your extension for about an hour now and I love it!

**Comment by xvxx** [comment]
Oh great! Thank you! I am loving LDPL, thank you for making it and sharing. 

Yes please feel free to post it and share the extension, I don't really use reddit. But if people find the plugin useful or want to contribute that would be wonderful.

**Comment by Lartu** [comment]
Thank you very much! It makes me so happy that you like it!

I'll post this on reddit and the website asap. Thanks to you for making and sharing this!

**Comment by xvxx** [comment]
Great! Btw what is dino's name? Is it okay to use in the README like I did? I apologize for the bad Photoshop.

**Comment by Lartu** [comment]
I love what you did in the README! And yes, it's absolutely okay! The name... It doesn't have a name yet. I mainly call it Ldplsaur or something along those lines, but I'm not even sure if it's a dinosaur or a dragon, so I'm not the one to ask ahahaha!

**Comment by xvxx** [comment]
Thanks! Oh okay, Ldplsaur makes the most sense yeah. Cuz someone told me it was a dragon named dino and I didn't think was it.

**Comment by Lartu** [comment]
Ahahahahaha no, I'm positive it's not ahah
