### ISSUE TITLE
LOAD FILE is not being highlighted

### ISSUE THREAD

**Issue by Lartu** [dvkt/vscode-ldpl#3]
Hi there! I'm studying for an exam at the moment so I can't fix this (I will do it later if you don't fix it first) but I've noticed that LOAD FILE is not being highlighted. I didn't find the `load` keyword on your syntax file so maybe that's what's missing.

Have a great day!

**Comment by xvxx** [comment]
Thanks, this and the other issue should be fixed in the new version!

**Comment by Lartu** [comment]
Great! Thank you!
