### ISSUE TITLE
WAIT x MILLISECONDS doesn't seem to be highlighted right

### ISSUE THREAD

**Issue by Lartu** [dvkt/vscode-ldpl#4]
![image](https://user-images.githubusercontent.com/11744462/56548350-43c3a980-6556-11e9-815a-21efdf9be14d.png)

It is being highlighted like this. I downloaded the extension from the visual studio marketplace. Is it up to date?

Sorry to bother you with so many issues, I love this! Have a nice day!

**Comment by xvxx** [comment]
Thanks! I redid the highlighting and broke some of it up the other day, this is a good catch :+1:

**Comment by Lartu** [comment]
Awesome! Thank you very much :3
